<!DOCTYPE html>
<html lang="en" data-admin-theme="{{ $adminThemeMode ?? 'dark' }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        @hasSection('title')
            @yield('title') — Admin
        @else
            Admin — {{ config('app.name', 'AuraNexus') }}
        @endif
    </title>

    @vite(['resources/css/app.css', 'resources/js/app.js'])

    {{-- Admin theme CSS (generated by ThemeService) --}}
    <style>{!! $adminThemeCss ?? '' !!}</style>

    @stack('head')
</head>

<body class="min-h-screen bg-[var(--an-bg)] text-[var(--an-text)]">
    <div class="flex min-h-screen">
        {{-- Sidebar --}}
        <x-admin.layout.sidebar />

        {{-- Main --}}
        <div class="flex min-w-0 flex-1 flex-col">
            {{-- Header --}}
            <x-admin.layout.header />

            {{-- Content --}}
            <main class="flex-1 p-6">
                @include('admin.partials.flash')
                @include('admin.partials.errors')

                @yield('content')
            </main>

            {{-- Footer --}}
            <x-admin.layout.footer />
        </div>
    </div>

    @stack('scripts')
</body>
</html>
