<!DOCTYPE html>
<<<<<<< HEAD
@php
    $mode = request()->cookie('theme_mode', 'dark');
    $mode = in_array($mode, ['dark','light'], true) ? $mode : 'dark';
@endphp
<html data-theme="{{ $mode }}">

=======
<html lang="en" data-admin-theme="{{ $adminThemeMode ?? 'dark' }}">
>>>>>>> origin/main
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        @hasSection('title')
            @yield('title') — Admin
        @else
            Admin — {{ config('app.name', 'AuraNexus') }}
        @endif
    </title>

    @vite(['resources/css/app.css', 'resources/js/app.js'])

<<<<<<< HEAD
    {{-- Theme CSS (generated by ThemeService) --}}
    @inject('theme', \App\Services\ThemeService::class)
    <style>
        {!! $theme->css($mode) !!}
    </style>

    {{-- Ensure HTML attribute is synced early (prevents edge cases / flash) --}}
    <script>
        (function () {
            document.documentElement.setAttribute('data-theme', @json($mode));
        })();
    </script>
=======
    {{-- Admin theme CSS (generated by ThemeService) --}}
    <style>{!! $adminThemeCss ?? '' !!}</style>
>>>>>>> origin/main

    @stack('head')
</head>

<<<<<<< HEAD
<body class="min-h-screen bg-[var(--an-bg)] text-[var(--an-text)] relative overflow-x-hidden">
    <!-- Ambient background glows -->
    <div class="pointer-events-none fixed inset-0 -z-10 overflow-hidden">
        <!-- Primary glow -->
        <div class="absolute -top-40 -left-40 h-[520px] w-[520px] rounded-full blur-3xl opacity-25
                    bg-[var(--an-link)]"></div>

        <!-- Secondary glow -->
        <div class="absolute top-32 -right-48 h-[620px] w-[620px] rounded-full blur-3xl opacity-20
                    bg-[var(--an-primary)]"></div>

        <!-- Tertiary glow -->
        <div class="absolute bottom-[-200px] left-[20%] h-[480px] w-[480px] rounded-full blur-[120px] opacity-10
                    bg-[var(--an-info)]"></div>
    </div>

    <div class="min-h-screen lg:flex">

        {{-- Mobile overlay --}}
        <div id="adminOverlay"
             class="fixed inset-0 z-40 hidden bg-black/60 lg:hidden"
             aria-hidden="true"></div>

        {{-- Sidebar wrapper --}}
        <div id="adminSidebar"
             class="fixed z-50 inset-y-0 left-0 w-72 -translate-x-full transition-transform duration-200
                    lg:static lg:translate-x-0 lg:inset-auto lg:shrink-0">
            <x-admin.layout.sidebar />
        </div>

        {{-- Main --}}
        <div class="flex min-w-0 flex-1 flex-col">
            <x-admin.layout.header />

            <main class="flex-1 p-4 sm:p-6">
                @include('admin.partials.flash')
                @include('admin.partials.errors')

                @yield('content')
            </main>

            <x-admin.layout.footer />
        </div>

    </div>

    <script>
        (function () {
            const sidebar = document.getElementById('adminSidebar');
            const overlay = document.getElementById('adminOverlay');
            const btn = document.getElementById('adminSidebarBtn');
            const closeBtn = document.getElementById('adminSidebarCloseBtn');

            function open() {
                if (window.innerWidth >= 1024) return;
                sidebar.classList.remove('-translate-x-full');
                overlay.classList.remove('hidden');
                document.body.classList.add('overflow-hidden');
            }

            function close() {
                if (window.innerWidth >= 1024) return;
                sidebar.classList.add('-translate-x-full');
                overlay.classList.add('hidden');
                document.body.classList.remove('overflow-hidden');
            }

            btn?.addEventListener('click', open);
            closeBtn?.addEventListener('click', close);
            overlay?.addEventListener('click', close);

            window.addEventListener('keydown', (e) => {
                if (e.key === 'Escape') close();
            });

            window.addEventListener('resize', () => {
                if (window.innerWidth >= 1024) {
                    overlay.classList.add('hidden');
                    document.body.classList.remove('overflow-hidden');
                }
            });
        })();
    </script>

=======
<body class="min-h-screen bg-[var(--an-bg)] text-[var(--an-text)]">
    <div class="flex min-h-screen">
        {{-- Sidebar --}}
        <x-admin.layout.sidebar />

        {{-- Main --}}
        <div class="flex min-w-0 flex-1 flex-col">
            {{-- Header --}}
            <x-admin.layout.header />

            {{-- Content --}}
            <main class="flex-1 p-6">
                @include('admin.partials.flash')
                @include('admin.partials.errors')

                @yield('content')
            </main>

            {{-- Footer --}}
            <x-admin.layout.footer />
        </div>
    </div>

>>>>>>> origin/main
    @stack('scripts')
</body>
</html>
