{{-- resources/views/layouts/auth.blade.php --}}
@php
    // ✅ Use cached site settings everywhere (same as home/nav/footer)
    $siteSettings = \App\Support\SiteSettings::public();

    $appName = ($siteSettings['site_name'] ?? '') ?: config('app.name', 'AuraNexus');
    $appBio  = ($siteSettings['site_subtitle'] ?? '') ?: (config('app.bio') ?? 'Build • Share • Learn');

    // SEO defaults for auth pages (usually noindex)
    $metaTitle = trim($__env->yieldContent('meta_title')) ?: trim($__env->yieldContent('title')) ?: $appName;
    $metaDescription = trim($__env->yieldContent('meta_description')) ?: $appBio;
    $canonical = trim($__env->yieldContent('canonical')) ?: url()->current();
    $robots = trim($__env->yieldContent('meta_robots')) ?: 'noindex,follow';

    $ogType  = trim($__env->yieldContent('og_type')) ?: 'website';
    $ogImage = trim($__env->yieldContent('og_image')) ?: null;

    // Theme mode (per-user)
    $mode = request()->cookie('theme_mode', 'dark');
    $mode = in_array($mode, ['dark','light'], true) ? $mode : 'dark';
@endphp

<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" data-theme="{{ $mode }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ $metaTitle }} - {{ $appName }}</title>
    <meta name="description" content="{{ $metaDescription }}">
    <link rel="canonical" href="{{ $canonical }}">

    {{-- ✅ Auth pages should not be indexed --}}
    <meta name="robots" content="{{ $robots }}">

    {{-- Open Graph --}}
    <meta property="og:site_name" content="{{ $appName }}">
    <meta property="og:title" content="{{ $metaTitle }}">
    <meta property="og:description" content="{{ $metaDescription }}">
    <meta property="og:type" content="{{ $ogType }}">
    <meta property="og:url" content="{{ $canonical }}">
    @if($ogImage)
        <meta property="og:image" content="{{ $ogImage }}">
    @endif

    {{-- Twitter --}}
    <meta name="twitter:card" content="{{ $ogImage ? 'summary_large_image' : 'summary' }}">
    <meta name="twitter:title" content="{{ $metaTitle }}">
    <meta name="twitter:description" content="{{ $metaDescription }}">
    @if($ogImage)
        <meta name="twitter:image" content="{{ $ogImage }}">
    @endif

    {{-- Security/UX helpful metas --}}
    <meta name="referrer" content="strict-origin-when-cross-origin">
    <meta name="format-detection" content="telephone=no">
    <meta name="color-scheme" content="dark light">

    {{-- App assets (use Vite, not public/css/app.css) --}}
    @vite(['resources/css/app.css','resources/js/app.js'])

    {{-- Theme CSS (generated by ThemeService) --}}
    @inject('theme', \App\Services\ThemeService::class)
    <style>
        {!! $theme->css($mode) !!}
        [x-cloak]{display:none !important;}
    </style>

    {{-- Ensure attribute is synced early --}}
    <script>
        (function () {
            document.documentElement.setAttribute('data-theme', @json($mode));
        })();
    </script>

    @stack('head')
</head>

<body class="min-h-screen bg-[var(--an-bg)] text-[var(--an-text)] overflow-x-hidden">
  @include('partials.nav')
    {{-- Ambient glows (match site) --}}
    <div class="pointer-events-none fixed inset-0 -z-10 overflow-hidden opacity-70">
        <div class="absolute -top-40 -left-40 h-[520px] w-[520px] rounded-full blur-3xl opacity-15 bg-[var(--an-link)]"></div>
        <div class="absolute top-24 -right-48 h-[620px] w-[620px] rounded-full blur-3xl opacity-12 bg-[var(--an-primary)]"></div>
        <div class="absolute bottom-[-220px] left-[25%] h-[520px] w-[520px] rounded-full blur-[140px] opacity-10 bg-[var(--an-info)]"></div>
    </div>

    <main class="min-h-screen flex justify-center py-5 sm:py-10">
        <div class="w-full max-w-md">

            <div class="sm:rounded-3xl border border-[var(--an-border)] bg-[color:var(--an-card)]/65 backdrop-blur-xl shadow-[0_16px_55px_rgba(0,0,0,0.28)] overflow-hidden">
                <div class="p-6 sm:p-7 border-b border-[var(--an-border)]">
                    <div class="text-xl sm:text-2xl font-extrabold tracking-tight text-center">
                        @yield('header')
                    </div>

                    <div class="mt-1 text-sm text-center text-[var(--an-text-muted)]">
                        {{ $appBio }}
                    </div>
                </div>

                <div class=" sm:p-7">

                    {{-- Flash success --}}
                    @if(session('success'))
                        <div class="mb-4 rounded-2xl border px-4 py-3 text-sm"
                             style="border-color: color-mix(in srgb, var(--an-success) 35%, var(--an-border));
                                    background: color-mix(in srgb, var(--an-success) 12%, transparent);
                                    color: color-mix(in srgb, var(--an-text) 85%, var(--an-success));">
                            {{ session('success') }}
                        </div>
                    @endif

                    {{-- Global validation errors (fallback) --}}
                    @if($errors->any())
                        <div class="mb-4 rounded-2xl border px-4 py-3 text-sm"
                             style="border-color: color-mix(in srgb, var(--an-danger) 35%, var(--an-border));
                                    background: color-mix(in srgb, var(--an-danger) 12%, transparent);
                                    color: color-mix(in srgb, var(--an-text) 85%, var(--an-danger));">
                            <div class="font-semibold">Please fix the following:</div>
                            <ul class="list-disc pl-5 mt-2 space-y-1">
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @yield('content')
                </div>
            </div>


        </div>
    </main>
    @include('partials.footer')
    @stack('scripts')
</body>
</html>
