<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@yield('title', 'Create Post')</title>

    {{-- SEO basics --}}
    <meta name="robots" content="noindex, nofollow">
    <meta name="referrer" content="strict-origin-when-cross-origin">

    {{-- CSRF --}}
    <meta name="csrf-token" content="{{ csrf_token() }}">

    {{-- Assets --}}
    @vite(['resources/css/app.css', 'resources/js/app.js'])

    {{-- Theme CSS (generated by ThemeService) --}}
    @php
        $mode = request()->cookie('theme_mode', 'dark');
        $mode = in_array($mode, ['dark','light'], true) ? $mode : 'dark';
    @endphp
    @inject('theme', \App\Services\ThemeService::class)
    <style>
        {!! $theme->css($mode) !!}
        [x-cloak]{display:none !important;}
    </style>

    {{-- Ensure attribute is synced early --}}
    <script>
        (function () {
            document.documentElement.setAttribute('data-theme', @json($mode));
        })();
    </script>

    @stack('head')
</head>

<body class="min-h-screen bg-[var(--an-bg)] text-[var(--an-text)] antialiased overflow-x-hidden">

    {{-- Ambient glows (match site vibe, subtle) --}}
    <div class="pointer-events-none fixed inset-0 -z-10 overflow-hidden opacity-60">
        <div class="absolute -top-40 -left-40 h-[520px] w-[520px] rounded-full blur-3xl opacity-15 bg-[var(--an-link)]"></div>
        <div class="absolute top-24 -right-48 h-[620px] w-[620px] rounded-full blur-3xl opacity-12 bg-[var(--an-primary)]"></div>
        <div class="absolute bottom-[-220px] left-[25%] h-[520px] w-[520px] rounded-full blur-[140px] opacity-10 bg-[var(--an-info)]"></div>
    </div>

    {{-- ✅ Use the same public navbar --}}
    @include('partials.nav')

    <main class="min-h-screen max-w-7xl mx-auto sm:px-6 lg:px-8 py-2 sm:py-6">
        {{-- Flash messages --}}
        @if (session('success'))
            <div class="mb-3 sm:mb-4 rounded-2xl border px-4 py-3 text-sm"
                 style="border-color: color-mix(in srgb, var(--an-success) 35%, var(--an-border));
                        background: color-mix(in srgb, var(--an-success) 12%, transparent);
                        color: color-mix(in srgb, var(--an-text) 85%, var(--an-success));">
                {{ session('success') }}
            </div>
        @endif

        @if (session('error'))
            <div class="mb-3 sm:mb-4 rounded-2xl border px-4 py-3 text-sm"
                 style="border-color: color-mix(in srgb, var(--an-danger) 35%, var(--an-border));
                        background: color-mix(in srgb, var(--an-danger) 12%, transparent);
                        color: color-mix(in srgb, var(--an-text) 85%, var(--an-danger));">
                {{ session('error') }}
            </div>
        @endif

        {{-- Validation errors --}}
        @if ($errors->any())
            <div class="mb-3 sm:mb-4 rounded-2xl border px-4 py-3 text-sm"
                 style="border-color: color-mix(in srgb, var(--an-danger) 35%, var(--an-border));
                        background: color-mix(in srgb, var(--an-danger) 12%, transparent);
                        color: color-mix(in srgb, var(--an-text) 85%, var(--an-danger));">
                <ul class="list-disc pl-5 space-y-1 text-sm">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {{-- Page content --}}
        <div class="py-2 sm:py-6">
            @yield('content') {{-- ✅ IMPORTANT --}}
        </div>
    </main>

    {{-- ✅ Use the same public footer --}}
    @include('partials.footer')

    @stack('scripts')
</body>
</html>
