@php
    use Illuminate\Support\Facades\Cache;

    $settings = $siteSettings ?? [];
    $siteName        = $settings['site_name'] ?? config('app.name', 'AuraNexus');
    $siteDescription = $settings['site_description'] ?? ('Explore the community on ' . $siteName . '.');
    $siteKeywords    = trim((string)($settings['site_keywords'] ?? ''));
    $themeColor      = $settings['site_theme_color'] ?? '#FF4268';
    $appName = $siteSettings['site_name'] ?? config('app.name', 'AuraNexus');
@endphp

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@yield('title', 'Create Post')</title>

    {{-- SEO basics --}}
    <meta name="robots" content="noindex, nofollow">
    <meta name="referrer" content="strict-origin-when-cross-origin">

    {{-- CSRF --}}
    <meta name="csrf-token" content="{{ csrf_token() }}">

    {{-- Assets --}}
    @vite(['resources/css/app.css', 'resources/js/app.js'])

    {{-- Theme CSS (generated by ThemeService) --}}
    @php
        $mode = request()->cookie('theme_mode', 'dark');
        $mode = in_array($mode, ['dark','light'], true) ? $mode : 'dark';
    @endphp
    @inject('theme', \App\Services\ThemeService::class)
    <style>
        {!! $theme->css($mode) !!}
        [x-cloak]{display:none !important;}
    </style>

    {{-- Ensure attribute is synced early --}}
    <script>
        (function () {
            document.documentElement.setAttribute('data-theme', @json($mode));
        })();
    </script>

    @stack('head')
</head>



<body class="min-h-screen bg-[var(--an-bg)] text-[var(--an-text)] overflow-x-hidden font-sans">

    @include('partials.background-layer')
    @include('partials.nav')
        {{-- Flash messages --}}
        @if (session('success'))
            <div class="mb-3 sm:mb-4 rounded-2xl border px-4 py-3 text-sm max-w-7xl mx-auto mt-3"
                 style="border-color: color-mix(in srgb, var(--an-success) 35%, var(--an-border));
                        background: color-mix(in srgb, var(--an-success) 12%, transparent);
                        color: color-mix(in srgb, var(--an-text) 85%, var(--an-success));">
                {{ session('success') }}
            </div>
        @endif

        @if (session('error'))
            <div class="mb-3 sm:mb-4 rounded-2xl border px-4 py-3 text-sm max-w-7xl mx-auto mt-3"
                 style="border-color: color-mix(in srgb, var(--an-danger) 35%, var(--an-border));
                        background: color-mix(in srgb, var(--an-danger) 12%, transparent);
                        color: color-mix(in srgb, var(--an-text) 85%, var(--an-danger));">
                {{ session('error') }}
            </div>
        @endif

        {{-- Validation errors --}}
        @if ($errors->any())
            <div class="mb-3 sm:mb-4 rounded-2xl border px-4 py-3 text-sm max-w-7xl mx-auto mt-3"
                 style="border-color: color-mix(in srgb, var(--an-danger) 35%, var(--an-border));
                        background: color-mix(in srgb, var(--an-danger) 12%, transparent);
                        color: color-mix(in srgb, var(--an-text) 85%, var(--an-danger));">
                <ul class="list-disc pl-5 space-y-1 text-sm">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    @include('partials.app-shell')

    @stack('scripts')






</body>
</html>
